### ISSUE TITLE
npm i18 errors out due to parsing issue

### ISSUE THREAD

**Issue by ermalsh** [benawad/dogehouse#1137]
**Describe the bug**
`npm run i18` errors out in the syncTranslation script.

**To Reproduce**
1. cd `kofta`
2. `npm run i18`
3. See error

**Expected behavior**
Work without erroring.

```
fs.readdirSync(join(__dirname, "../public/locales")).forEach((locale) => {                                               
SyntaxError: Unexpected token } in JSON at position 6641
    at JSON.parse (<anonymous>)
    at dogehouse\kofta\scripts\syncTranslations.ts:22:20
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (dogehouse\kofta\scripts\syncTranslations.ts:12:54)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Module.m._compile (dogehouse\kofta\node_modules\ts-node\src\index.ts:1056:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Object.require.extensions.<computed> [as .ts] (dogehouse\kofta\node_modules\ts-node\src\index.ts:1059:12)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! kofta@0.1.0 sync:i18: `ts-node --project scripts/tsconfig.json scripts/syncTranslations.ts`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the kofta@0.1.0 sync:i18 script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     AppData\Roaming\npm-cache\_logs\2021-03-16T23_15_07_061Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! kofta@0.1.0 i18: `npm run gen:i18:keys && npm run sync:i18`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the kofta@0.1.0 i18 script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     AppData\Roaming\npm-cache\_logs\2021-03-16T23_15_07_089Z-debug.log```

**Comment by ermalsh** [comment]
Error due to: 
Line 197 in `kofta/public/locales/nb/translation.json` malformed JSON.
