### ISSUE TITLE
When running kofta locally by npm run start:staging I get an error

### ISSUE THREAD

**Issue by degrootruben** [benawad/dogehouse#1161]
Stacktrace:
```
TypeError: anymatch is not a function
    at FSWatcher._isIgnored (dogehouse\kofta\node_modules\watchpack\node_modules\chokidar\index.js:770:25)
    at NodeFsHandler._addToNodeFs (dogehouse\kofta\node_modules\watchpack\node_modules\chokidar\lib\nodefs-handler.js:581:16)
    at dogehouse\kofta\node_modules\watchpack\node_modules\chokidar\index.js:445:47        
    at Array.map (<anonymous>)
    at FSWatcher.add (dogehouse\kofta\node_modules\watchpack\node_modules\chokidar\index.js:444:13)
    at Object.watch (dogehouse\kofta\node_modules\watchpack\node_modules\chokidar\index.js:963:11)
    at new DirectoryWatcher (dogehouse\kofta\node_modules\watchpack\lib\DirectoryWatcher.js:53:26)
    at WatcherManager.getDirectoryWatcher (dogehouse\kofta\node_modules\watchpack\lib\watcherManager.js:18:33)
    at WatcherManager.watchFile (dogehouse\kofta\node_modules\watchpack\lib\watcherManager.js:28:14)
    at Watchpack.<anonymous> (dogehouse\kofta\node_modules\watchpack\lib\watchpack.js:38:49)
```
How would I fix this so I can run the React frontend locally?

**Comment by nadirabbas** [comment]
try  re-running `npm install`

**Comment by advcu987** [comment]
I had a similar issue and fixed it by updating node to version 14 
this helped: 
https://stackoverflow.com/questions/65311936/node-error-when-i-run-npm-with-laravel-breeze

**Comment by degrootruben** [comment]
> try re-running `npm install`

doesnt work sadly...

**Comment by degrootruben** [comment]
> I had a similar issue and fixed it by updating node to version 14
> this helped:
> https://stackoverflow.com/questions/65311936/node-error-when-i-run-npm-with-laravel-breeze

This fix doens't work as well.

**Comment by goldyydev** [comment]
Does this still occur?

Try to delete the dogehouse folder and re-add it.

</br>
<sup><i>If I answered your question, please make sure to close this issue as we're already flooded with them</i></sup>

**Comment by degrootruben** [comment]
@goldyydev yes this somehow made it work again, thanks
sorry for the late reply, i'll close the issue now
