### ISSUE TITLE
Unable to npm run i18

### ISSUE THREAD

**Issue by amitojsingh366** [benawad/dogehouse#1323]
**Describe the bug**
I tried adding new keys to translations and ran `npm run i18` and it failed.

**To Reproduce**
1. Add a new key in `public/locales/en/translations.json`
2. Run `npm run i18`

**Expected behavior**
The translations should be synced

**Screenshots**
![image](https://user-images.githubusercontent.com/35400192/111851484-61594380-8924-11eb-8729-de0e4e88b704.png)

**What device are you on?**
Windows 10
**Additional context**
Was making overlay for electron app so needed to add the `set keybind` translation key.

**Output**
```

PS E:\Projects\dogehouse\kofta> npm run i18

> kofta@0.1.0 i18 E:\Projects\dogehouse\kofta
> npm run gen:i18:keys && npm run sync:i18   


> kofta@0.1.0 gen:i18:keys E:\Projects\dogehouse\kofta
> ts-node --project scripts/tsconfig.json scripts/generateTranslationTypes.ts


> kofta@0.1.0 sync:i18 E:\Projects\dogehouse\kofta
> ts-node --project scripts/tsconfig.json scripts/syncTranslations.ts


E:\Projects\dogehouse\kofta\scripts\syncTranslations.ts:12
fs.readdirSync(join(__dirname, "../public/locales")).forEach((locale) => {
                                                     ^
SyntaxError: Unexpected token < in JSON at position 5388
    at JSON.parse (<anonymous>)
    at E:\Projects\dogehouse\kofta\scripts\syncTranslations.ts:22:20
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (E:\Projects\dogehouse\kofta\scripts\syncTranslations.ts:12:54)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Module.m._compile (E:\Projects\dogehouse\kofta\node_modules\ts-node\src\index.ts:1056:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.require.extensions.<computed> [as .ts] (E:\Projects\dogehouse\kofta\node_modules\ts-node\src\index.ts:1059:12)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! kofta@0.1.0 sync:i18: `ts-node --project scripts/tsconfig.json scripts/syncTranslations.ts`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the kofta@0.1.0 sync:i18 script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\amito\AppData\Roaming\npm-cache\_logs\2021-03-19T23_27_42_002Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! kofta@0.1.0 i18: `npm run gen:i18:keys && npm run sync:i18`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the kofta@0.1.0 i18 script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by ermalsh** [comment]
Check for a stray or missing comma in one of the Translation.json files.
