### ISSUE TITLE
Storybook doesn't work

### ISSUE THREAD

**Issue by samarmohan** [benawad/dogehouse#1544]
**Describe the bug**
Trying to run storybook in kibbeh. When I build it

**To Reproduce**
1. `cd kibbeh`
2. `yarn`
3. `yarn build-storybook`
5. Try `yarn storybook`
6. See other error

**Error**
When building
```
ERR! => Failed to build the preview
ERR! Module not found: Error: Can't resolve '../ui/Header' in 'C:\Users\Samar\Documents\Coding\dogehouse\kibbeh\src\stories'
ERR! ModuleNotFoundError: Module not found: Error: Can't resolve '../ui/Header' in 'C:\Users\Samar\Documents\Coding\dogehouse\kibbeh\src\stories'
ERR!     at C:\Users\Samar\Documents\Coding\dogehouse\kibbeh\node_modules\webpack\lib\Compilation.js:925:10
ERR!     at C:\Users\Samar\Documents\Coding\dogehouse\kibbeh\node_modules\webpack\lib\NormalModuleFactory.js:401:22
ERR!     at C:\Users\Samar\Documents\Coding\dogehouse\kibbeh\node_modules\webpack\lib\NormalModuleFactory.js:130:21
ERR!     at C:\Users\Samar\Documents\Coding\dogehouse\kibbeh\node_modules\webpack\lib\NormalModuleFactory.js:224:22
ERR!     at C:\Users\Samar\Documents\Coding\dogehouse\kibbeh\node_modules\neo-async\async.js:2830:7
ERR!     at C:\Users\Samar\Documents\Coding\dogehouse\kibbeh\node_modules\neo-async\async.js:6877:13
ERR!     at C:\Users\Samar\Documents\Coding\dogehouse\kibbeh\node_modules\webpack\lib\NormalModuleFactory.js:214:25
ERR!     at C:\Users\Samar\Documents\Coding\dogehouse\kibbeh\node_modules\webpack\node_modules\enhanced-resolve\lib\Resolver.js:213:14
ERR!     at C:\Users\Samar\Documents\Coding\dogehouse\kibbeh\node_modules\webpack\node_modules\enhanced-resolve\lib\Resolver.js:285:5
ERR!     at eval (eval at create (C:\Users\Samar\Documents\Coding\dogehouse\kibbeh\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
ERR!     at C:\Users\Samar\Documents\Coding\dogehouse\kibbeh\node_modules\webpack\node_modules\enhanced-resolve\lib\UnsafeCachePlugin.js:44:7
ERR!     at C:\Users\Samar\Documents\Coding\dogehouse\kibbeh\node_modules\webpack\node_modules\enhanced-resolve\lib\Resolver.js:285:5
ERR!     at eval (eval at create (C:\Users\Samar\Documents\Coding\dogehouse\kibbeh\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)  
ERR!     at C:\Users\Samar\Documents\Coding\dogehouse\kibbeh\node_modules\webpack\node_modules\enhanced-resolve\lib\Resolver.js:285:5
ERR!     at eval (eval at create (C:\Users\Samar\Documents\Coding\dogehouse\kibbeh\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:27:1)  
ERR!     at C:\Users\Samar\Documents\Coding\dogehouse\kibbeh\node_modules\webpack\node_modules\enhanced-resolve\lib\DescriptionFilePlugin.js:67:43        
ERR!  ModuleNotFoundError: Module not found: Error: Can't resolve '../ui/Header' in 'C:\Users\Samar\Documents\Coding\dogehouse\kibbeh\src\stories'        
ERR!     at C:\Users\Samar\Documents\Coding\dogehouse\kibbeh\node_modules\webpack\lib\Compilation.js:925:10
ERR!     at C:\Users\Samar\Documents\Coding\dogehouse\kibbeh\node_modules\webpack\lib\NormalModuleFactory.js:401:22
ERR!     at C:\Users\Samar\Documents\Coding\dogehouse\kibbeh\node_modules\webpack\lib\NormalModuleFactory.js:130:21
ERR!     at C:\Users\Samar\Documents\Coding\dogehouse\kibbeh\node_modules\webpack\lib\NormalModuleFactory.js:224:22
ERR!     at C:\Users\Samar\Documents\Coding\dogehouse\kibbeh\node_modules\neo-async\async.js:2830:7
ERR!     at C:\Users\Samar\Documents\Coding\dogehouse\kibbeh\node_modules\neo-async\async.js:6877:13
ERR!     at C:\Users\Samar\Documents\Coding\dogehouse\kibbeh\node_modules\webpack\lib\NormalModuleFactory.js:214:25
ERR!     at C:\Users\Samar\Documents\Coding\dogehouse\kibbeh\node_modules\webpack\node_modules\enhanced-resolve\lib\Resolver.js:213:14
ERR!     at C:\Users\Samar\Documents\Coding\dogehouse\kibbeh\node_modules\webpack\node_modules\enhanced-resolve\lib\Resolver.js:285:5
ERR!     at eval (eval at create (C:\Users\Samar\Documents\Coding\dogehouse\kibbeh\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)  
ERR!     at C:\Users\Samar\Documents\Coding\dogehouse\kibbeh\node_modules\webpack\node_modules\enhanced-resolve\lib\UnsafeCachePlugin.js:44:7
ERR!     at C:\Users\Samar\Documents\Coding\dogehouse\kibbeh\node_modules\webpack\node_modules\enhanced-resolve\lib\Resolver.js:285:5
ERR!     at eval (eval at create (C:\Users\Samar\Documents\Coding\dogehouse\kibbeh\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
ERR!     at C:\Users\Samar\Documents\Coding\dogehouse\kibbeh\node_modules\webpack\node_modules\enhanced-resolve\lib\Resolver.js:285:5
ERR!     at eval (eval at create (C:\Users\Samar\Documents\Coding\dogehouse\kibbeh\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:27:1)  
ERR!     at C:\Users\Samar\Documents\Coding\dogehouse\kibbeh\node_modules\webpack\node_modules\enhanced-resolve\lib\DescriptionFilePlugin.js:67:43        
ERR! resolve '../ui/Header' in 'C:\Users\Samar\Documents\Coding\dogehouse\kibbeh\src\stories'
ERR!   using description file: C:\Users\Samar\Documents\Coding\dogehouse\kibbeh\package.json (relative path: ./src/stories)
ERR!     Field 'browser' doesn't contain a valid alias configuration
ERR!     using description file: C:\Users\Samar\Documents\Coding\dogehouse\kibbeh\package.json (relative path: ./src/ui/Header)
ERR!       no extension
ERR!         Field 'browser' doesn't contain a valid alias configuration
ERR!         C:\Users\Samar\Documents\Coding\dogehouse\kibbeh\src\ui\Header is not a file
ERR!       .mjs
ERR!         Field 'browser' doesn't contain a valid alias configuration
ERR!         C:\Users\Samar\Documents\Coding\dogehouse\kibbeh\src\ui\Header.mjs doesn't exist
ERR!       .js
ERR!         Field 'browser' doesn't contain a valid alias configuration
ERR!         C:\Users\Samar\Documents\Coding\dogehouse\kibbeh\src\ui\Header.js doesn't exist
ERR!       .jsx
ERR!         Field 'browser' doesn't contain a valid alias configuration
ERR!         C:\Users\Samar\Documents\Coding\dogehouse\kibbeh\src\ui\Header.jsx doesn't exist
ERR!       .ts
ERR!         Field 'browser' doesn't contain a valid alias configuration
ERR!         C:\Users\Samar\Documents\Coding\dogehouse\kibbeh\src\ui\Header.ts doesn't exist
ERR!       .tsx
ERR!         Field 'browser' doesn't contain a valid alias configuration
ERR!         C:\Users\Samar\Documents\Coding\dogehouse\kibbeh\src\ui\Header.tsx doesn't exist
ERR!       .json
ERR!         Field 'browser' doesn't contain a valid alias configuration
ERR!         C:\Users\Samar\Documents\Coding\dogehouse\kibbeh\src\ui\Header.json doesn't exist
ERR!       .cjs
ERR!         Field 'browser' doesn't contain a valid alias configuration
ERR!         C:\Users\Samar\Documents\Coding\dogehouse\kibbeh\src\ui\Header.cjs doesn't exist
ERR!       as directory
ERR!         existing directory
ERR!           using path: C:\Users\Samar\Documents\Coding\dogehouse\kibbeh\src\ui\Header\index
ERR!             using description file: C:\Users\Samar\Documents\Coding\dogehouse\kibbeh\package.json (relative path: ./src/ui/Header/index)
ERR!               no extension
ERR!                 Field 'browser' doesn't contain a valid alias configuration
ERR!                 C:\Users\Samar\Documents\Coding\dogehouse\kibbeh\src\ui\Header\index doesn't exist
ERR!               .mjs
ERR!                 Field 'browser' doesn't contain a valid alias configuration
ERR!                 C:\Users\Samar\Documents\Coding\dogehouse\kibbeh\src\ui\Header\index.mjs doesn't exist
ERR!               .js
ERR!                 Field 'browser' doesn't contain a valid alias configuration
ERR!                 C:\Users\Samar\Documents\Coding\dogehouse\kibbeh\src\ui\Header\index.js doesn't exist
ERR!               .jsx
ERR!                 Field 'browser' doesn't contain a valid alias configuration
ERR!                 C:\Users\Samar\Documents\Coding\dogehouse\kibbeh\src\ui\Header\index.jsx doesn't exist
ERR!               .ts
ERR!                 Field 'browser' doesn't contain a valid alias configuration
ERR!                 C:\Users\Samar\Documents\Coding\dogehouse\kibbeh\src\ui\Header\index.ts doesn't exist
ERR!               .tsx
ERR!                 Field 'browser' doesn't contain a valid alias configuration
ERR!                 C:\Users\Samar\Documents\Coding\dogehouse\kibbeh\src\ui\Header\index.tsx doesn't exist
ERR!               .json
ERR!                 Field 'browser' doesn't contain a valid alias configuration
ERR!                 C:\Users\Samar\Documents\Coding\dogehouse\kibbeh\src\ui\Header\index.json doesn't exist
ERR!               .cjs
ERR!                 Field 'browser' doesn't contain a valid alias configuration
ERR!                 C:\Users\Samar\Documents\Coding\dogehouse\kibbeh\src\ui\Header\index.cjs doesn't exist
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
````
When running
```
ERROR in ./src/stories/Header.story.tsx
Module not found: Error: Can't resolve '../ui/Header' in 'C:\Users\Samar\Documents\Coding\dogehouse\kibbeh\src\stories'
 @ ./src/stories/Header.story.tsx 35:0-34 42:13-19 65:27-33
 @ ./src/stories sync ^\.(?:(?:^|[\\/]|(?:(?:(?!(?:^|[\\/])\.).)*?)[\\/])(?!\.)(?=.)[^\\/]*?\.story\.(ts|tsx|js|jsx|mdx))$
 @ ./.storybook/generated-stories-entry.js
 @ multi ./node_modules/@storybook/core-server/dist/cjs/globals/polyfills.js ./node_modules/@storybook/core-server/dist/cjs/globals/globals.js ./.storybook/storybook-init-framework-entry.js ./node_modules/@storybook/addon-docs/dist/esm/frameworks/common/config.js-generated-other-entry.js ./node_modules/@storybook/addon-docs/dist/esm/frameworks/react/config.js-generated-other-entry.js ./node_modules/@storybook/addon-links/dist/esm/preset/addDecorator.js-generated-other-entry.js ./node_modules/@storybook/addon-actions/dist/esm/preset/addDecorator.js-generated-other-entry.js ./node_modules/@storybook/addon-actions/dist/esm/preset/addArgs.js-generated-other-entry.js ./node_modules/@storybook/addon-backgrounds/dist/esm/preset/addDecorator.js-generated-other-entry.js ./node_modules/@storybook/addon-backgrounds/dist/esm/preset/addParameter.js-generated-other-entry.js ./.storybook/preview.js-generated-config-entry.js ./.storybook/generated-stories-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined
Child HtmlWebpackCompiler:
                          Asset      Size               Chunks  Chunk Names
    __child-HtmlWebpackPlugin_0  6.32 KiB  HtmlWebpackPlugin_0  HtmlWebpackPlugin_0
    Entrypoint HtmlWebpackPlugin_0 = __child-HtmlWebpackPlugin_0
    [./node_modules/html-webpack-plugin/lib/loader.js!./node_modules/@storybook/core-common/dist/cjs/templates/index.ejs] 2 KiB {HtmlWebpackPlugin_0} [built]
ModuleNotFoundError: Module not found: Error: Can't resolve '../ui/Header' in 'C:\Users\Samar\Documents\Coding\dogehouse\kibbeh\src\stories'
    at C:\Users\Samar\Documents\Coding\dogehouse\kibbeh\node_modules\webpack\lib\Compilation.js:925:10
    at C:\Users\Samar\Documents\Coding\dogehouse\kibbeh\node_modules\webpack\lib\NormalModuleFactory.js:401:22
    at C:\Users\Samar\Documents\Coding\dogehouse\kibbeh\node_modules\webpack\lib\NormalModuleFactory.js:130:21
    at C:\Users\Samar\Documents\Coding\dogehouse\kibbeh\node_modules\webpack\lib\NormalModuleFactory.js:224:22
    at C:\Users\Samar\Documents\Coding\dogehouse\kibbeh\node_modules\neo-async\async.js:2830:7
    at C:\Users\Samar\Documents\Coding\dogehouse\kibbeh\node_modules\neo-async\async.js:6877:13
    at C:\Users\Samar\Documents\Coding\dogehouse\kibbeh\node_modules\webpack\lib\NormalModuleFactory.js:214:25
    at C:\Users\Samar\Documents\Coding\dogehouse\kibbeh\node_modules\webpack\node_modules\enhanced-resolve\lib\Resolver.js:213:14
    at C:\Users\Samar\Documents\Coding\dogehouse\kibbeh\node_modules\webpack\node_modules\enhanced-resolve\lib\Resolver.js:285:5
    at eval (eval at create (C:\Users\Samar\Documents\Coding\dogehouse\kibbeh\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)       
    at C:\Users\Samar\Documents\Coding\dogehouse\kibbeh\node_modules\webpack\node_modules\enhanced-resolve\lib\UnsafeCachePlugin.js:44:7
    at C:\Users\Samar\Documents\Coding\dogehouse\kibbeh\node_modules\webpack\node_modules\enhanced-resolve\lib\Resolver.js:285:5
    at eval (eval at create (C:\Users\Samar\Documents\Coding\dogehouse\kibbeh\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)       
    at C:\Users\Samar\Documents\Coding\dogehouse\kibbeh\node_modules\webpack\node_modules\enhanced-resolve\lib\Resolver.js:285:5
    at eval (eval at create (C:\Users\Samar\Documents\Coding\dogehouse\kibbeh\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:27:1)       
    at C:\Users\Samar\Documents\Coding\dogehouse\kibbeh\node_modules\webpack\node_modules\enhanced-resolve\lib\DescriptionFilePlugin.js:67:43
resolve '../ui/Header' in 'C:\Users\Samar\Documents\Coding\dogehouse\kibbeh\src\stories'
  using description file: C:\Users\Samar\Documents\Coding\dogehouse\kibbeh\package.json (relative path: ./src/stories)
    Field 'browser' doesn't contain a valid alias configuration
    using description file: C:\Users\Samar\Documents\Coding\dogehouse\kibbeh\package.json (relative path: ./src/ui/Header)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        C:\Users\Samar\Documents\Coding\dogehouse\kibbeh\src\ui\Header is not a file
      .mjs
        Field 'browser' doesn't contain a valid alias configuration
        C:\Users\Samar\Documents\Coding\dogehouse\kibbeh\src\ui\Header.mjs doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        C:\Users\Samar\Documents\Coding\dogehouse\kibbeh\src\ui\Header.js doesn't exist
      .jsx
        Field 'browser' doesn't contain a valid alias configuration
        C:\Users\Samar\Documents\Coding\dogehouse\kibbeh\src\ui\Header.jsx doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        C:\Users\Samar\Documents\Coding\dogehouse\kibbeh\src\ui\Header.ts doesn't exist
      .tsx
        Field 'browser' doesn't contain a valid alias configuration
        C:\Users\Samar\Documents\Coding\dogehouse\kibbeh\src\ui\Header.tsx doesn't exist
      .json
        Field 'browser' doesn't contain a valid alias configuration
        C:\Users\Samar\Documents\Coding\dogehouse\kibbeh\src\ui\Header.json doesn't exist
      .cjs
        Field 'browser' doesn't contain a valid alias configuration
        C:\Users\Samar\Documents\Coding\dogehouse\kibbeh\src\ui\Header.cjs doesn't exist
      as directory
        existing directory
          using path: C:\Users\Samar\Documents\Coding\dogehouse\kibbeh\src\ui\Header\index
            using description file: C:\Users\Samar\Documents\Coding\dogehouse\kibbeh\package.json (relative path: ./src/ui/Header/index)
              no extension
                Field 'browser' doesn't contain a valid alias configuration
                C:\Users\Samar\Documents\Coding\dogehouse\kibbeh\src\ui\Header\index doesn't exist
              .mjs
                Field 'browser' doesn't contain a valid alias configuration
                C:\Users\Samar\Documents\Coding\dogehouse\kibbeh\src\ui\Header\index.mjs doesn't exist
              .js
                Field 'browser' doesn't contain a valid alias configuration
                C:\Users\Samar\Documents\Coding\dogehouse\kibbeh\src\ui\Header\index.js doesn't exist
              .jsx
                Field 'browser' doesn't contain a valid alias configuration
                C:\Users\Samar\Documents\Coding\dogehouse\kibbeh\src\ui\Header\index.jsx doesn't exist
              .ts
                Field 'browser' doesn't contain a valid alias configuration
                C:\Users\Samar\Documents\Coding\dogehouse\kibbeh\src\ui\Header\index.ts doesn't exist
              .tsx
                Field 'browser' doesn't contain a valid alias configuration
                C:\Users\Samar\Documents\Coding\dogehouse\kibbeh\src\ui\Header\index.tsx doesn't exist
              .json
                Field 'browser' doesn't contain a valid alias configuration
                C:\Users\Samar\Documents\Coding\dogehouse\kibbeh\src\ui\Header\index.json doesn't exist
              .cjs
                Field 'browser' doesn't contain a valid alias configuration
                C:\Users\Samar\Documents\Coding\dogehouse\kibbeh\src\ui\Header\index.cjs doesn't exist

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Expected behavior**
Storybook builds and runs.

**Screenshots**

**What device are you on?**
Windows 10

**Comment by cursorial** [comment]
Looks like `../ui/Header` doesn't exist. It was removed here: https://github.com/benawad/dogehouse/commit/5ef207c184db56b209d2d83bbbe547cbaf6e45fb#diff-65cc59190f1e030664134e564aa2d6b11b55555e57ebfbc8bc9e0470338a4a2cL1-L88

Will probably need to re-write the Header story to get this to build.
