### ISSUE TITLE
Desktop app crashes immediately on macOS

### ISSUE THREAD

**Issue by cjdenio** [benawad/dogehouse#1605]
**Describe the bug**

When I try to open the Electron app on macOS, it crashes without even saying hello :(

```
Uncaught Exception:
Error: dlopen(/var/folders/t0/k54c4zw55kq2hqhnn7p21lgr0000gn/T/.com.electron.dogehouse.6OOCdl, 1): no suitable image found.  Did find:
/var/folders/t0/k54c4zw55kq2hqhnn7p21lgr0000gn/T/.com.electron.dogehouse.6OOCdl: code signature in (/var/folders/t0/k54c4zw55kq2hqhnn7p21lgr0000gn/T/.com.electron.dogehouse.6OOCdl) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
/var/folders/t0/k54c4zw55kq2hqhnn7p21lgr0000gn/T/.com.electron.dogehouse.6OOCdl: stat() failed with errno=17
at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1812)
at Object.Module._extensions..node (internal/modules/cjs/loader.js:1203:18)
at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2039)
at Module.load (internal/modules/cjs/loader.js:992:32)
at Module._load (internal/modules/cjs/loader.js:885:14)
at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
at Module.require (internal/modules/cjs/loader.js:1032:19)
at require (internal/modules/cjs/helpers.js:72:18)
at load (/Applications/DogeHouse.app/Contents/Resources/app.asar/node_modules/node-gyp-build/index.js:21:10)
at Object.<anonymous> (/Applications/DogeHouse.app/Contents/Resources/app.asar/node_modules/electron-overlay-window/dist/index.js:8:38)
```

**To Reproduce**
1. Open the app
2. Observe error
3. Rethink life choices

**Expected behavior**

I expected it to work

**Screenshots**

<img width="283" alt="Screen Shot 2021-03-26 at 12 29 11 PM" src="https://user-images.githubusercontent.com/34525547/112663154-e06fdf80-8e2e-11eb-9f8a-3dcb80b84824.png">

**What device are you on?**

I'm on an M1 MacBook Air.

**Additional context**

I was eating lunch at the time

**Comment by mmattbtw** [comment]
+1, I can replicate this on an M1 MacBook Air too.

**Comment by cjdenio** [comment]
oops #1569 already exists

i swear i searched for issues before opening this, but that one remained elusive 🤔
