### ISSUE TITLE
handle mediasoup timeout error

### ISSUE THREAD

**Issue by benawad** [benawad/dogehouse#1730]
```
(node:528868) UnhandledPromiseRejectionWarning: Error: Channel request timeout
    at Timeout._onTimeout (/home/holopanio/projects/dogehouse-music/src/dogehouse.js-audio/node_modules/mediasoup-client-aiortc/lib/Channel.js:146:29)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
(node:528868) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
```

**Comment by ghost** [comment]
Remove this line from the code [if it is there] -> .catch(error => { throw error})
